export const vehicles = [
  {
    id: "polo_10_tsi",
    make: "Volkswagen",
    model: "Polo 1.0 TSI + DSG",
    engineType: "1.0L TSI Petrol (Turbo EA211)",
    displacementCc: 999,
    cylinders: 3,
    baseHp: 110,
    baseTorque: 175,
    rpmLimit: 6500,
    weightKg: 1072,
    baseBoostBar: 0.8,
    gearbox: "7-Speed DSG (DQ200)",
    dragCoef: 0.32,
    frontalAreaSqM: 2.0,
    baseKmpl: 18.2,
    strokeMm: 76.4,
    boreMm: 74.5,
    gearboxTorqueLimitNm: 250,
    optimumRpmRange: { start: 2000, end: 5500 },
    notes: "Very popular tuner hatchback. The DQ200 dry-clutch gearbox is brilliant but highly sensitive to torque spikes above 250 Nm without a TCU (Transmission Control Unit) tune."
  },
  {
    id: "fortuner_28_d4d",
    make: "Toyota",
    model: "Fortuner 2.8 D-4D",
    engineType: "2.8L D-4D Diesel (Turbo 1GD-FTV)",
    displacementCc: 2755,
    cylinders: 4,
    baseHp: 201,
    baseTorque: 500,
    rpmLimit: 4500,
    weightKg: 2180,
    baseBoostBar: 1.4,
    gearbox: "6-Speed Torque Converter Automatic",
    dragCoef: 0.38,
    frontalAreaSqM: 2.8,
    baseKmpl: 14.4,
    strokeMm: 103.6,
    boreMm: 92.0,
    gearboxTorqueLimitNm: 650,
    optimumRpmRange: { start: 1600, end: 3200 },
    notes: "Massive road presence and reliable engine. Heavily tuned in India using diesel tuning boxes or custom ECU remaps. Heavyweight SUV requires substantial torque to feel fast."
  },
  {
    id: "bmw_f10_530d",
    make: "BMW",
    model: "5 Series 530d (F10)",
    engineType: "3.0L Inline-6 Diesel (Turbo N57)",
    displacementCc: 2993,
    cylinders: 6,
    baseHp: 258,
    baseTorque: 560,
    rpmLimit: 5000,
    weightKg: 1795,
    baseBoostBar: 1.6,
    gearbox: "8-Speed Automatic (ZF 8HP70)",
    dragCoef: 0.28,
    frontalAreaSqM: 2.22,
    baseKmpl: 14.7,
    strokeMm: 90.0,
    boreMm: 84.0,
    gearboxTorqueLimitNm: 700,
    optimumRpmRange: { start: 1500, end: 4000 },
    notes: "Ultimate used luxury tuner project. The N57 inline-6 diesel engine is a torque monster. The stock ZF 8HP70 gearbox can easily withstand heavy tunes up to 700 Nm safely."
  },
  {
    id: "bmw_f10_520d",
    make: "BMW",
    model: "5 Series 520d (F10)",
    engineType: "2.0L Inline-4 Diesel (Turbo N47/B47)",
    displacementCc: 1995,
    cylinders: 4,
    baseHp: 184,
    baseTorque: 380,
    rpmLimit: 5000,
    weightKg: 1705,
    baseBoostBar: 1.3,
    gearbox: "8-Speed Automatic (ZF 8HP45)",
    dragCoef: 0.28,
    frontalAreaSqM: 2.22,
    baseKmpl: 16.8,
    strokeMm: 90.0,
    boreMm: 84.0,
    gearboxTorqueLimitNm: 450,
    optimumRpmRange: { start: 1750, end: 3500 },
    notes: "Highly popular executive cruiser. Great fuel efficiency, decent tuning potential, and responds excellently to Stage 1 remaps."
  },
  {
    id: "honda_city_15_cvt",
    make: "Honda",
    model: "City 1.5 i-VTEC CVT",
    engineType: "1.5L i-VTEC Petrol (NA L15)",
    displacementCc: 1498,
    cylinders: 4,
    baseHp: 119,
    baseTorque: 145,
    rpmLimit: 7000,
    weightKg: 1153,
    baseBoostBar: 0.0,
    gearbox: "7-Step CVT (Continuously Variable)",
    dragCoef: 0.29,
    frontalAreaSqM: 2.1,
    baseKmpl: 18.4,
    strokeMm: 89.5,
    boreMm: 73.0,
    gearboxTorqueLimitNm: 180,
    optimumRpmRange: { start: 4300, end: 6600 },
    notes: "High-revving naturally aspirated DOHC i-VTEC engine. Responds brilliantly to bolt-on cold air intakes and free-flow headers. CVT transmission belts are sensitive to high torque, needing a TCU remap for heavy tuning."
  }
];
